### ISSUE TITLE
Support for Php 8.1

### ISSUE THREAD

**Issue by Chris53897** [karser/PayumSaferpay#10]
Hi.
Thanks for your work.

Are there any plans for an update to support php 8.1? 
php: ^7.2 || ^8.0
https://packagist.org/packages/payum/core

I just took over an project with this dependency and this is a blocker for us to move to php 8.1.

Greetz

**Comment by karser** [comment]
Hello,
No plans yet but PR is welcomed.
This change requires adding php 8.0 and 8.1 to the CI pipeline.
We'll need to check if Travis still works for us.
https://app.travis-ci.com/github/karser/PayumSaferpay
If it doesn't - we will need to migrate to Github actions.

**Comment by solverat** [comment]
+1 for moving to github actions since it‘s a quite easy task. We also don‘t have any plans yet but I guess we’re able to provide an PR in the next upcoming weeks.

**Comment by karser** [comment]
@Chris53897 please update to v0.3.3
https://github.com/karser/PayumSaferpay/releases/tag/v0.3.3

**Comment by Chris53897** [comment]
@karser thanks
